// This file is generated by rust-protobuf 3.7.2. Do not edit
// .proto file is parsed by protoc 31.1
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `vault_v1.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_2;

// @@protoc_insertion_point(message:proton_pass_vault_v1.VaultDisplayPreferences)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct VaultDisplayPreferences {
    // message fields
    // @@protoc_insertion_point(field:proton_pass_vault_v1.VaultDisplayPreferences.icon)
    pub icon: ::protobuf::EnumOrUnknown<VaultIcon>,
    // @@protoc_insertion_point(field:proton_pass_vault_v1.VaultDisplayPreferences.color)
    pub color: ::protobuf::EnumOrUnknown<VaultColor>,
    // special fields
    // @@protoc_insertion_point(special_field:proton_pass_vault_v1.VaultDisplayPreferences.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a VaultDisplayPreferences {
    fn default() -> &'a VaultDisplayPreferences {
        <VaultDisplayPreferences as ::protobuf::Message>::default_instance()
    }
}

impl VaultDisplayPreferences {
    pub fn new() -> VaultDisplayPreferences {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "icon",
            |m: &VaultDisplayPreferences| { &m.icon },
            |m: &mut VaultDisplayPreferences| { &mut m.icon },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "color",
            |m: &VaultDisplayPreferences| { &m.color },
            |m: &mut VaultDisplayPreferences| { &mut m.color },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<VaultDisplayPreferences>(
            "VaultDisplayPreferences",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for VaultDisplayPreferences {
    const NAME: &'static str = "VaultDisplayPreferences";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.icon = is.read_enum_or_unknown()?;
                },
                16 => {
                    self.color = is.read_enum_or_unknown()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.icon != ::protobuf::EnumOrUnknown::new(VaultIcon::ICON_UNSPECIFIED) {
            my_size += ::protobuf::rt::int32_size(1, self.icon.value());
        }
        if self.color != ::protobuf::EnumOrUnknown::new(VaultColor::COLOR_UNSPECIFIED) {
            my_size += ::protobuf::rt::int32_size(2, self.color.value());
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.icon != ::protobuf::EnumOrUnknown::new(VaultIcon::ICON_UNSPECIFIED) {
            os.write_enum(1, ::protobuf::EnumOrUnknown::value(&self.icon))?;
        }
        if self.color != ::protobuf::EnumOrUnknown::new(VaultColor::COLOR_UNSPECIFIED) {
            os.write_enum(2, ::protobuf::EnumOrUnknown::value(&self.color))?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> VaultDisplayPreferences {
        VaultDisplayPreferences::new()
    }

    fn clear(&mut self) {
        self.icon = ::protobuf::EnumOrUnknown::new(VaultIcon::ICON_UNSPECIFIED);
        self.color = ::protobuf::EnumOrUnknown::new(VaultColor::COLOR_UNSPECIFIED);
        self.special_fields.clear();
    }

    fn default_instance() -> &'static VaultDisplayPreferences {
        static instance: VaultDisplayPreferences = VaultDisplayPreferences {
            icon: ::protobuf::EnumOrUnknown::from_i32(0),
            color: ::protobuf::EnumOrUnknown::from_i32(0),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for VaultDisplayPreferences {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("VaultDisplayPreferences").unwrap()).clone()
    }
}

impl ::std::fmt::Display for VaultDisplayPreferences {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for VaultDisplayPreferences {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:proton_pass_vault_v1.Vault)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct Vault {
    // message fields
    // @@protoc_insertion_point(field:proton_pass_vault_v1.Vault.name)
    pub name: ::std::string::String,
    // @@protoc_insertion_point(field:proton_pass_vault_v1.Vault.description)
    pub description: ::std::string::String,
    // @@protoc_insertion_point(field:proton_pass_vault_v1.Vault.display)
    pub display: ::protobuf::MessageField<VaultDisplayPreferences>,
    // special fields
    // @@protoc_insertion_point(special_field:proton_pass_vault_v1.Vault.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Vault {
    fn default() -> &'a Vault {
        <Vault as ::protobuf::Message>::default_instance()
    }
}

impl Vault {
    pub fn new() -> Vault {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(3);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "name",
            |m: &Vault| { &m.name },
            |m: &mut Vault| { &mut m.name },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "description",
            |m: &Vault| { &m.description },
            |m: &mut Vault| { &mut m.description },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, VaultDisplayPreferences>(
            "display",
            |m: &Vault| { &m.display },
            |m: &mut Vault| { &mut m.display },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Vault>(
            "Vault",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for Vault {
    const NAME: &'static str = "Vault";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.name = is.read_string()?;
                },
                18 => {
                    self.description = is.read_string()?;
                },
                26 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.display)?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.name.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.name);
        }
        if !self.description.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.description);
        }
        if let Some(v) = self.display.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.name.is_empty() {
            os.write_string(1, &self.name)?;
        }
        if !self.description.is_empty() {
            os.write_string(2, &self.description)?;
        }
        if let Some(v) = self.display.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(3, v, os)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Vault {
        Vault::new()
    }

    fn clear(&mut self) {
        self.name.clear();
        self.description.clear();
        self.display.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Vault {
        static instance: Vault = Vault {
            name: ::std::string::String::new(),
            description: ::std::string::String::new(),
            display: ::protobuf::MessageField::none(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for Vault {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("Vault").unwrap()).clone()
    }
}

impl ::std::fmt::Display for Vault {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Vault {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:proton_pass_vault_v1.VaultIcon)
pub enum VaultIcon {
    // @@protoc_insertion_point(enum_value:proton_pass_vault_v1.VaultIcon.ICON_UNSPECIFIED)
    ICON_UNSPECIFIED = 0,
    // @@protoc_insertion_point(enum_value:proton_pass_vault_v1.VaultIcon.ICON_CUSTOM)
    ICON_CUSTOM = 1,
    // @@protoc_insertion_point(enum_value:proton_pass_vault_v1.VaultIcon.ICON1)
    ICON1 = 2,
    // @@protoc_insertion_point(enum_value:proton_pass_vault_v1.VaultIcon.ICON2)
    ICON2 = 3,
    // @@protoc_insertion_point(enum_value:proton_pass_vault_v1.VaultIcon.ICON3)
    ICON3 = 4,
    // @@protoc_insertion_point(enum_value:proton_pass_vault_v1.VaultIcon.ICON4)
    ICON4 = 5,
    // @@protoc_insertion_point(enum_value:proton_pass_vault_v1.VaultIcon.ICON5)
    ICON5 = 6,
    // @@protoc_insertion_point(enum_value:proton_pass_vault_v1.VaultIcon.ICON6)
    ICON6 = 7,
    // @@protoc_insertion_point(enum_value:proton_pass_vault_v1.VaultIcon.ICON7)
    ICON7 = 8,
    // @@protoc_insertion_point(enum_value:proton_pass_vault_v1.VaultIcon.ICON8)
    ICON8 = 9,
    // @@protoc_insertion_point(enum_value:proton_pass_vault_v1.VaultIcon.ICON9)
    ICON9 = 10,
    // @@protoc_insertion_point(enum_value:proton_pass_vault_v1.VaultIcon.ICON10)
    ICON10 = 11,
    // @@protoc_insertion_point(enum_value:proton_pass_vault_v1.VaultIcon.ICON11)
    ICON11 = 12,
    // @@protoc_insertion_point(enum_value:proton_pass_vault_v1.VaultIcon.ICON12)
    ICON12 = 13,
    // @@protoc_insertion_point(enum_value:proton_pass_vault_v1.VaultIcon.ICON13)
    ICON13 = 14,
    // @@protoc_insertion_point(enum_value:proton_pass_vault_v1.VaultIcon.ICON14)
    ICON14 = 15,
    // @@protoc_insertion_point(enum_value:proton_pass_vault_v1.VaultIcon.ICON15)
    ICON15 = 16,
    // @@protoc_insertion_point(enum_value:proton_pass_vault_v1.VaultIcon.ICON16)
    ICON16 = 17,
    // @@protoc_insertion_point(enum_value:proton_pass_vault_v1.VaultIcon.ICON17)
    ICON17 = 18,
    // @@protoc_insertion_point(enum_value:proton_pass_vault_v1.VaultIcon.ICON18)
    ICON18 = 19,
    // @@protoc_insertion_point(enum_value:proton_pass_vault_v1.VaultIcon.ICON19)
    ICON19 = 20,
    // @@protoc_insertion_point(enum_value:proton_pass_vault_v1.VaultIcon.ICON20)
    ICON20 = 21,
    // @@protoc_insertion_point(enum_value:proton_pass_vault_v1.VaultIcon.ICON21)
    ICON21 = 22,
    // @@protoc_insertion_point(enum_value:proton_pass_vault_v1.VaultIcon.ICON22)
    ICON22 = 23,
    // @@protoc_insertion_point(enum_value:proton_pass_vault_v1.VaultIcon.ICON23)
    ICON23 = 24,
    // @@protoc_insertion_point(enum_value:proton_pass_vault_v1.VaultIcon.ICON24)
    ICON24 = 25,
    // @@protoc_insertion_point(enum_value:proton_pass_vault_v1.VaultIcon.ICON25)
    ICON25 = 26,
    // @@protoc_insertion_point(enum_value:proton_pass_vault_v1.VaultIcon.ICON26)
    ICON26 = 27,
    // @@protoc_insertion_point(enum_value:proton_pass_vault_v1.VaultIcon.ICON27)
    ICON27 = 28,
    // @@protoc_insertion_point(enum_value:proton_pass_vault_v1.VaultIcon.ICON28)
    ICON28 = 29,
    // @@protoc_insertion_point(enum_value:proton_pass_vault_v1.VaultIcon.ICON29)
    ICON29 = 30,
    // @@protoc_insertion_point(enum_value:proton_pass_vault_v1.VaultIcon.ICON30)
    ICON30 = 31,
}

impl ::protobuf::Enum for VaultIcon {
    const NAME: &'static str = "VaultIcon";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<VaultIcon> {
        match value {
            0 => ::std::option::Option::Some(VaultIcon::ICON_UNSPECIFIED),
            1 => ::std::option::Option::Some(VaultIcon::ICON_CUSTOM),
            2 => ::std::option::Option::Some(VaultIcon::ICON1),
            3 => ::std::option::Option::Some(VaultIcon::ICON2),
            4 => ::std::option::Option::Some(VaultIcon::ICON3),
            5 => ::std::option::Option::Some(VaultIcon::ICON4),
            6 => ::std::option::Option::Some(VaultIcon::ICON5),
            7 => ::std::option::Option::Some(VaultIcon::ICON6),
            8 => ::std::option::Option::Some(VaultIcon::ICON7),
            9 => ::std::option::Option::Some(VaultIcon::ICON8),
            10 => ::std::option::Option::Some(VaultIcon::ICON9),
            11 => ::std::option::Option::Some(VaultIcon::ICON10),
            12 => ::std::option::Option::Some(VaultIcon::ICON11),
            13 => ::std::option::Option::Some(VaultIcon::ICON12),
            14 => ::std::option::Option::Some(VaultIcon::ICON13),
            15 => ::std::option::Option::Some(VaultIcon::ICON14),
            16 => ::std::option::Option::Some(VaultIcon::ICON15),
            17 => ::std::option::Option::Some(VaultIcon::ICON16),
            18 => ::std::option::Option::Some(VaultIcon::ICON17),
            19 => ::std::option::Option::Some(VaultIcon::ICON18),
            20 => ::std::option::Option::Some(VaultIcon::ICON19),
            21 => ::std::option::Option::Some(VaultIcon::ICON20),
            22 => ::std::option::Option::Some(VaultIcon::ICON21),
            23 => ::std::option::Option::Some(VaultIcon::ICON22),
            24 => ::std::option::Option::Some(VaultIcon::ICON23),
            25 => ::std::option::Option::Some(VaultIcon::ICON24),
            26 => ::std::option::Option::Some(VaultIcon::ICON25),
            27 => ::std::option::Option::Some(VaultIcon::ICON26),
            28 => ::std::option::Option::Some(VaultIcon::ICON27),
            29 => ::std::option::Option::Some(VaultIcon::ICON28),
            30 => ::std::option::Option::Some(VaultIcon::ICON29),
            31 => ::std::option::Option::Some(VaultIcon::ICON30),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<VaultIcon> {
        match str {
            "ICON_UNSPECIFIED" => ::std::option::Option::Some(VaultIcon::ICON_UNSPECIFIED),
            "ICON_CUSTOM" => ::std::option::Option::Some(VaultIcon::ICON_CUSTOM),
            "ICON1" => ::std::option::Option::Some(VaultIcon::ICON1),
            "ICON2" => ::std::option::Option::Some(VaultIcon::ICON2),
            "ICON3" => ::std::option::Option::Some(VaultIcon::ICON3),
            "ICON4" => ::std::option::Option::Some(VaultIcon::ICON4),
            "ICON5" => ::std::option::Option::Some(VaultIcon::ICON5),
            "ICON6" => ::std::option::Option::Some(VaultIcon::ICON6),
            "ICON7" => ::std::option::Option::Some(VaultIcon::ICON7),
            "ICON8" => ::std::option::Option::Some(VaultIcon::ICON8),
            "ICON9" => ::std::option::Option::Some(VaultIcon::ICON9),
            "ICON10" => ::std::option::Option::Some(VaultIcon::ICON10),
            "ICON11" => ::std::option::Option::Some(VaultIcon::ICON11),
            "ICON12" => ::std::option::Option::Some(VaultIcon::ICON12),
            "ICON13" => ::std::option::Option::Some(VaultIcon::ICON13),
            "ICON14" => ::std::option::Option::Some(VaultIcon::ICON14),
            "ICON15" => ::std::option::Option::Some(VaultIcon::ICON15),
            "ICON16" => ::std::option::Option::Some(VaultIcon::ICON16),
            "ICON17" => ::std::option::Option::Some(VaultIcon::ICON17),
            "ICON18" => ::std::option::Option::Some(VaultIcon::ICON18),
            "ICON19" => ::std::option::Option::Some(VaultIcon::ICON19),
            "ICON20" => ::std::option::Option::Some(VaultIcon::ICON20),
            "ICON21" => ::std::option::Option::Some(VaultIcon::ICON21),
            "ICON22" => ::std::option::Option::Some(VaultIcon::ICON22),
            "ICON23" => ::std::option::Option::Some(VaultIcon::ICON23),
            "ICON24" => ::std::option::Option::Some(VaultIcon::ICON24),
            "ICON25" => ::std::option::Option::Some(VaultIcon::ICON25),
            "ICON26" => ::std::option::Option::Some(VaultIcon::ICON26),
            "ICON27" => ::std::option::Option::Some(VaultIcon::ICON27),
            "ICON28" => ::std::option::Option::Some(VaultIcon::ICON28),
            "ICON29" => ::std::option::Option::Some(VaultIcon::ICON29),
            "ICON30" => ::std::option::Option::Some(VaultIcon::ICON30),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [VaultIcon] = &[
        VaultIcon::ICON_UNSPECIFIED,
        VaultIcon::ICON_CUSTOM,
        VaultIcon::ICON1,
        VaultIcon::ICON2,
        VaultIcon::ICON3,
        VaultIcon::ICON4,
        VaultIcon::ICON5,
        VaultIcon::ICON6,
        VaultIcon::ICON7,
        VaultIcon::ICON8,
        VaultIcon::ICON9,
        VaultIcon::ICON10,
        VaultIcon::ICON11,
        VaultIcon::ICON12,
        VaultIcon::ICON13,
        VaultIcon::ICON14,
        VaultIcon::ICON15,
        VaultIcon::ICON16,
        VaultIcon::ICON17,
        VaultIcon::ICON18,
        VaultIcon::ICON19,
        VaultIcon::ICON20,
        VaultIcon::ICON21,
        VaultIcon::ICON22,
        VaultIcon::ICON23,
        VaultIcon::ICON24,
        VaultIcon::ICON25,
        VaultIcon::ICON26,
        VaultIcon::ICON27,
        VaultIcon::ICON28,
        VaultIcon::ICON29,
        VaultIcon::ICON30,
    ];
}

impl ::protobuf::EnumFull for VaultIcon {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("VaultIcon").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = *self as usize;
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for VaultIcon {
    fn default() -> Self {
        VaultIcon::ICON_UNSPECIFIED
    }
}

impl VaultIcon {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<VaultIcon>("VaultIcon")
    }
}

#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:proton_pass_vault_v1.VaultColor)
pub enum VaultColor {
    // @@protoc_insertion_point(enum_value:proton_pass_vault_v1.VaultColor.COLOR_UNSPECIFIED)
    COLOR_UNSPECIFIED = 0,
    // @@protoc_insertion_point(enum_value:proton_pass_vault_v1.VaultColor.COLOR_CUSTOM)
    COLOR_CUSTOM = 1,
    // @@protoc_insertion_point(enum_value:proton_pass_vault_v1.VaultColor.COLOR1)
    COLOR1 = 2,
    // @@protoc_insertion_point(enum_value:proton_pass_vault_v1.VaultColor.COLOR2)
    COLOR2 = 3,
    // @@protoc_insertion_point(enum_value:proton_pass_vault_v1.VaultColor.COLOR3)
    COLOR3 = 4,
    // @@protoc_insertion_point(enum_value:proton_pass_vault_v1.VaultColor.COLOR4)
    COLOR4 = 5,
    // @@protoc_insertion_point(enum_value:proton_pass_vault_v1.VaultColor.COLOR5)
    COLOR5 = 6,
    // @@protoc_insertion_point(enum_value:proton_pass_vault_v1.VaultColor.COLOR6)
    COLOR6 = 7,
    // @@protoc_insertion_point(enum_value:proton_pass_vault_v1.VaultColor.COLOR7)
    COLOR7 = 8,
    // @@protoc_insertion_point(enum_value:proton_pass_vault_v1.VaultColor.COLOR8)
    COLOR8 = 9,
    // @@protoc_insertion_point(enum_value:proton_pass_vault_v1.VaultColor.COLOR9)
    COLOR9 = 10,
    // @@protoc_insertion_point(enum_value:proton_pass_vault_v1.VaultColor.COLOR10)
    COLOR10 = 11,
}

impl ::protobuf::Enum for VaultColor {
    const NAME: &'static str = "VaultColor";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<VaultColor> {
        match value {
            0 => ::std::option::Option::Some(VaultColor::COLOR_UNSPECIFIED),
            1 => ::std::option::Option::Some(VaultColor::COLOR_CUSTOM),
            2 => ::std::option::Option::Some(VaultColor::COLOR1),
            3 => ::std::option::Option::Some(VaultColor::COLOR2),
            4 => ::std::option::Option::Some(VaultColor::COLOR3),
            5 => ::std::option::Option::Some(VaultColor::COLOR4),
            6 => ::std::option::Option::Some(VaultColor::COLOR5),
            7 => ::std::option::Option::Some(VaultColor::COLOR6),
            8 => ::std::option::Option::Some(VaultColor::COLOR7),
            9 => ::std::option::Option::Some(VaultColor::COLOR8),
            10 => ::std::option::Option::Some(VaultColor::COLOR9),
            11 => ::std::option::Option::Some(VaultColor::COLOR10),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<VaultColor> {
        match str {
            "COLOR_UNSPECIFIED" => ::std::option::Option::Some(VaultColor::COLOR_UNSPECIFIED),
            "COLOR_CUSTOM" => ::std::option::Option::Some(VaultColor::COLOR_CUSTOM),
            "COLOR1" => ::std::option::Option::Some(VaultColor::COLOR1),
            "COLOR2" => ::std::option::Option::Some(VaultColor::COLOR2),
            "COLOR3" => ::std::option::Option::Some(VaultColor::COLOR3),
            "COLOR4" => ::std::option::Option::Some(VaultColor::COLOR4),
            "COLOR5" => ::std::option::Option::Some(VaultColor::COLOR5),
            "COLOR6" => ::std::option::Option::Some(VaultColor::COLOR6),
            "COLOR7" => ::std::option::Option::Some(VaultColor::COLOR7),
            "COLOR8" => ::std::option::Option::Some(VaultColor::COLOR8),
            "COLOR9" => ::std::option::Option::Some(VaultColor::COLOR9),
            "COLOR10" => ::std::option::Option::Some(VaultColor::COLOR10),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [VaultColor] = &[
        VaultColor::COLOR_UNSPECIFIED,
        VaultColor::COLOR_CUSTOM,
        VaultColor::COLOR1,
        VaultColor::COLOR2,
        VaultColor::COLOR3,
        VaultColor::COLOR4,
        VaultColor::COLOR5,
        VaultColor::COLOR6,
        VaultColor::COLOR7,
        VaultColor::COLOR8,
        VaultColor::COLOR9,
        VaultColor::COLOR10,
    ];
}

impl ::protobuf::EnumFull for VaultColor {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("VaultColor").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = *self as usize;
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for VaultColor {
    fn default() -> Self {
        VaultColor::COLOR_UNSPECIFIED
    }
}

impl VaultColor {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<VaultColor>("VaultColor")
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x0evault_v1.proto\x12\x14proton_pass_vault_v1\"\x86\x01\n\x17VaultDis\
    playPreferences\x123\n\x04icon\x18\x01\x20\x01(\x0e2\x1f.proton_pass_vau\
    lt_v1.VaultIconR\x04icon\x126\n\x05color\x18\x02\x20\x01(\x0e2\x20.proto\
    n_pass_vault_v1.VaultColorR\x05color\"\x86\x01\n\x05Vault\x12\x12\n\x04n\
    ame\x18\x01\x20\x01(\tR\x04name\x12\x20\n\x0bdescription\x18\x02\x20\x01\
    (\tR\x0bdescription\x12G\n\x07display\x18\x03\x20\x01(\x0b2-.proton_pass\
    _vault_v1.VaultDisplayPreferencesR\x07display*\x91\x03\n\tVaultIcon\x12\
    \x14\n\x10ICON_UNSPECIFIED\x10\0\x12\x0f\n\x0bICON_CUSTOM\x10\x01\x12\t\
    \n\x05ICON1\x10\x02\x12\t\n\x05ICON2\x10\x03\x12\t\n\x05ICON3\x10\x04\
    \x12\t\n\x05ICON4\x10\x05\x12\t\n\x05ICON5\x10\x06\x12\t\n\x05ICON6\x10\
    \x07\x12\t\n\x05ICON7\x10\x08\x12\t\n\x05ICON8\x10\t\x12\t\n\x05ICON9\
    \x10\n\x12\n\n\x06ICON10\x10\x0b\x12\n\n\x06ICON11\x10\x0c\x12\n\n\x06IC\
    ON12\x10\r\x12\n\n\x06ICON13\x10\x0e\x12\n\n\x06ICON14\x10\x0f\x12\n\n\
    \x06ICON15\x10\x10\x12\n\n\x06ICON16\x10\x11\x12\n\n\x06ICON17\x10\x12\
    \x12\n\n\x06ICON18\x10\x13\x12\n\n\x06ICON19\x10\x14\x12\n\n\x06ICON20\
    \x10\x15\x12\n\n\x06ICON21\x10\x16\x12\n\n\x06ICON22\x10\x17\x12\n\n\x06\
    ICON23\x10\x18\x12\n\n\x06ICON24\x10\x19\x12\n\n\x06ICON25\x10\x1a\x12\n\
    \n\x06ICON26\x10\x1b\x12\n\n\x06ICON27\x10\x1c\x12\n\n\x06ICON28\x10\x1d\
    \x12\n\n\x06ICON29\x10\x1e\x12\n\n\x06ICON30\x10\x1f*\xae\x01\n\nVaultCo\
    lor\x12\x15\n\x11COLOR_UNSPECIFIED\x10\0\x12\x10\n\x0cCOLOR_CUSTOM\x10\
    \x01\x12\n\n\x06COLOR1\x10\x02\x12\n\n\x06COLOR2\x10\x03\x12\n\n\x06COLO\
    R3\x10\x04\x12\n\n\x06COLOR4\x10\x05\x12\n\n\x06COLOR5\x10\x06\x12\n\n\
    \x06COLOR6\x10\x07\x12\n\n\x06COLOR7\x10\x08\x12\n\n\x06COLOR8\x10\t\x12\
    \n\n\x06COLOR9\x10\n\x12\x0b\n\x07COLOR10\x10\x0bb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(2);
            messages.push(VaultDisplayPreferences::generated_message_descriptor_data());
            messages.push(Vault::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(2);
            enums.push(VaultIcon::generated_enum_descriptor_data());
            enums.push(VaultColor::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
