// This file is generated by rust-protobuf 3.7.2. Do not edit
// .proto file is parsed by protoc 31.1
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `synthetic_extended_v1.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_2;

// @@protoc_insertion_point(message:synthetic_extended_v1.Inner)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct Inner {
    // message fields
    // @@protoc_insertion_point(field:synthetic_extended_v1.Inner.a)
    pub a: ::std::string::String,
    // @@protoc_insertion_point(field:synthetic_extended_v1.Inner.b)
    pub b: ::std::string::String,
    // special fields
    // @@protoc_insertion_point(special_field:synthetic_extended_v1.Inner.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Inner {
    fn default() -> &'a Inner {
        <Inner as ::protobuf::Message>::default_instance()
    }
}

impl Inner {
    pub fn new() -> Inner {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "a",
            |m: &Inner| { &m.a },
            |m: &mut Inner| { &mut m.a },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "b",
            |m: &Inner| { &m.b },
            |m: &mut Inner| { &mut m.b },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Inner>(
            "Inner",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for Inner {
    const NAME: &'static str = "Inner";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.a = is.read_string()?;
                },
                18 => {
                    self.b = is.read_string()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.a.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.a);
        }
        if !self.b.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.b);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.a.is_empty() {
            os.write_string(1, &self.a)?;
        }
        if !self.b.is_empty() {
            os.write_string(2, &self.b)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Inner {
        Inner::new()
    }

    fn clear(&mut self) {
        self.a.clear();
        self.b.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Inner {
        static instance: Inner = Inner {
            a: ::std::string::String::new(),
            b: ::std::string::String::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for Inner {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("Inner").unwrap()).clone()
    }
}

impl ::std::fmt::Display for Inner {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Inner {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:synthetic_extended_v1.ExtraMessage)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct ExtraMessage {
    // message fields
    // @@protoc_insertion_point(field:synthetic_extended_v1.ExtraMessage.value)
    pub value: ::std::string::String,
    // special fields
    // @@protoc_insertion_point(special_field:synthetic_extended_v1.ExtraMessage.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a ExtraMessage {
    fn default() -> &'a ExtraMessage {
        <ExtraMessage as ::protobuf::Message>::default_instance()
    }
}

impl ExtraMessage {
    pub fn new() -> ExtraMessage {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "value",
            |m: &ExtraMessage| { &m.value },
            |m: &mut ExtraMessage| { &mut m.value },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<ExtraMessage>(
            "ExtraMessage",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for ExtraMessage {
    const NAME: &'static str = "ExtraMessage";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.value = is.read_string()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.value.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.value);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.value.is_empty() {
            os.write_string(1, &self.value)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> ExtraMessage {
        ExtraMessage::new()
    }

    fn clear(&mut self) {
        self.value.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static ExtraMessage {
        static instance: ExtraMessage = ExtraMessage {
            value: ::std::string::String::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for ExtraMessage {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("ExtraMessage").unwrap()).clone()
    }
}

impl ::std::fmt::Display for ExtraMessage {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ExtraMessage {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:synthetic_extended_v1.Record)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct Record {
    // message fields
    // @@protoc_insertion_point(field:synthetic_extended_v1.Record.title)
    pub title: ::std::string::String,
    // @@protoc_insertion_point(field:synthetic_extended_v1.Record.note)
    pub note: ::std::option::Option<::std::string::String>,
    // @@protoc_insertion_point(field:synthetic_extended_v1.Record.tags)
    pub tags: ::std::vec::Vec<::std::string::String>,
    // @@protoc_insertion_point(field:synthetic_extended_v1.Record.inner)
    pub inner: ::protobuf::MessageField<Inner>,
    // @@protoc_insertion_point(field:synthetic_extended_v1.Record.items)
    pub items: ::std::vec::Vec<Inner>,
    // @@protoc_insertion_point(field:synthetic_extended_v1.Record.count)
    pub count: i32,
    // @@protoc_insertion_point(field:synthetic_extended_v1.Record.kind)
    pub kind: ::protobuf::EnumOrUnknown<Kind>,
    // @@protoc_insertion_point(field:synthetic_extended_v1.Record.attrs)
    pub attrs: ::std::collections::HashMap<::std::string::String, ::std::string::String>,
    // @@protoc_insertion_point(field:synthetic_extended_v1.Record.extra_scalar)
    pub extra_scalar: ::std::string::String,
    // @@protoc_insertion_point(field:synthetic_extended_v1.Record.extra_optional)
    pub extra_optional: ::std::option::Option<::std::string::String>,
    // @@protoc_insertion_point(field:synthetic_extended_v1.Record.extra_repeated)
    pub extra_repeated: ::std::vec::Vec<::std::string::String>,
    // @@protoc_insertion_point(field:synthetic_extended_v1.Record.extra_message)
    pub extra_message: ::protobuf::MessageField<ExtraMessage>,
    // @@protoc_insertion_point(field:synthetic_extended_v1.Record.extra_map)
    pub extra_map: ::std::collections::HashMap<::std::string::String, ::std::string::String>,
    // @@protoc_insertion_point(field:synthetic_extended_v1.Record.extra_varint)
    pub extra_varint: i64,
    // message oneof groups
    pub payload: ::std::option::Option<record::Payload>,
    // special fields
    // @@protoc_insertion_point(special_field:synthetic_extended_v1.Record.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Record {
    fn default() -> &'a Record {
        <Record as ::protobuf::Message>::default_instance()
    }
}

impl Record {
    pub fn new() -> Record {
        ::std::default::Default::default()
    }

    // string text = 8;

    pub fn text(&self) -> &str {
        match self.payload {
            ::std::option::Option::Some(record::Payload::Text(ref v)) => v,
            _ => "",
        }
    }

    pub fn clear_text(&mut self) {
        self.payload = ::std::option::Option::None;
    }

    pub fn has_text(&self) -> bool {
        match self.payload {
            ::std::option::Option::Some(record::Payload::Text(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_text(&mut self, v: ::std::string::String) {
        self.payload = ::std::option::Option::Some(record::Payload::Text(v))
    }

    // Mutable pointer to the field.
    pub fn mut_text(&mut self) -> &mut ::std::string::String {
        if let ::std::option::Option::Some(record::Payload::Text(_)) = self.payload {
        } else {
            self.payload = ::std::option::Option::Some(record::Payload::Text(::std::string::String::new()));
        }
        match self.payload {
            ::std::option::Option::Some(record::Payload::Text(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_text(&mut self) -> ::std::string::String {
        if self.has_text() {
            match self.payload.take() {
                ::std::option::Option::Some(record::Payload::Text(v)) => v,
                _ => panic!(),
            }
        } else {
            ::std::string::String::new()
        }
    }

    // .synthetic_extended_v1.Inner nested = 9;

    pub fn nested(&self) -> &Inner {
        match self.payload {
            ::std::option::Option::Some(record::Payload::Nested(ref v)) => v,
            _ => <Inner as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_nested(&mut self) {
        self.payload = ::std::option::Option::None;
    }

    pub fn has_nested(&self) -> bool {
        match self.payload {
            ::std::option::Option::Some(record::Payload::Nested(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_nested(&mut self, v: Inner) {
        self.payload = ::std::option::Option::Some(record::Payload::Nested(v))
    }

    // Mutable pointer to the field.
    pub fn mut_nested(&mut self) -> &mut Inner {
        if let ::std::option::Option::Some(record::Payload::Nested(_)) = self.payload {
        } else {
            self.payload = ::std::option::Option::Some(record::Payload::Nested(Inner::new()));
        }
        match self.payload {
            ::std::option::Option::Some(record::Payload::Nested(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_nested(&mut self) -> Inner {
        if self.has_nested() {
            match self.payload.take() {
                ::std::option::Option::Some(record::Payload::Nested(v)) => v,
                _ => panic!(),
            }
        } else {
            Inner::new()
        }
    }

    // bytes blob = 106;

    pub fn blob(&self) -> &[u8] {
        match self.payload {
            ::std::option::Option::Some(record::Payload::Blob(ref v)) => v,
            _ => &[],
        }
    }

    pub fn clear_blob(&mut self) {
        self.payload = ::std::option::Option::None;
    }

    pub fn has_blob(&self) -> bool {
        match self.payload {
            ::std::option::Option::Some(record::Payload::Blob(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_blob(&mut self, v: ::std::vec::Vec<u8>) {
        self.payload = ::std::option::Option::Some(record::Payload::Blob(v))
    }

    // Mutable pointer to the field.
    pub fn mut_blob(&mut self) -> &mut ::std::vec::Vec<u8> {
        if let ::std::option::Option::Some(record::Payload::Blob(_)) = self.payload {
        } else {
            self.payload = ::std::option::Option::Some(record::Payload::Blob(::std::vec::Vec::new()));
        }
        match self.payload {
            ::std::option::Option::Some(record::Payload::Blob(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_blob(&mut self) -> ::std::vec::Vec<u8> {
        if self.has_blob() {
            match self.payload.take() {
                ::std::option::Option::Some(record::Payload::Blob(v)) => v,
                _ => panic!(),
            }
        } else {
            ::std::vec::Vec::new()
        }
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(17);
        let mut oneofs = ::std::vec::Vec::with_capacity(1);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "title",
            |m: &Record| { &m.title },
            |m: &mut Record| { &mut m.title },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "note",
            |m: &Record| { &m.note },
            |m: &mut Record| { &mut m.note },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "tags",
            |m: &Record| { &m.tags },
            |m: &mut Record| { &mut m.tags },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, Inner>(
            "inner",
            |m: &Record| { &m.inner },
            |m: &mut Record| { &mut m.inner },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "items",
            |m: &Record| { &m.items },
            |m: &mut Record| { &mut m.items },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "count",
            |m: &Record| { &m.count },
            |m: &mut Record| { &mut m.count },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "kind",
            |m: &Record| { &m.kind },
            |m: &mut Record| { &mut m.kind },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_deref_has_get_set_simpler_accessor::<_, _>(
            "text",
            Record::has_text,
            Record::text,
            Record::set_text,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, Inner>(
            "nested",
            Record::has_nested,
            Record::nested,
            Record::mut_nested,
            Record::set_nested,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_deref_has_get_set_simpler_accessor::<_, _>(
            "blob",
            Record::has_blob,
            Record::blob,
            Record::set_blob,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_map_simpler_accessor_new::<_, _>(
            "attrs",
            |m: &Record| { &m.attrs },
            |m: &mut Record| { &mut m.attrs },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "extra_scalar",
            |m: &Record| { &m.extra_scalar },
            |m: &mut Record| { &mut m.extra_scalar },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "extra_optional",
            |m: &Record| { &m.extra_optional },
            |m: &mut Record| { &mut m.extra_optional },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "extra_repeated",
            |m: &Record| { &m.extra_repeated },
            |m: &mut Record| { &mut m.extra_repeated },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, ExtraMessage>(
            "extra_message",
            |m: &Record| { &m.extra_message },
            |m: &mut Record| { &mut m.extra_message },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_map_simpler_accessor_new::<_, _>(
            "extra_map",
            |m: &Record| { &m.extra_map },
            |m: &mut Record| { &mut m.extra_map },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "extra_varint",
            |m: &Record| { &m.extra_varint },
            |m: &mut Record| { &mut m.extra_varint },
        ));
        oneofs.push(record::Payload::generated_oneof_descriptor_data());
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Record>(
            "Record",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for Record {
    const NAME: &'static str = "Record";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.title = is.read_string()?;
                },
                18 => {
                    self.note = ::std::option::Option::Some(is.read_string()?);
                },
                26 => {
                    self.tags.push(is.read_string()?);
                },
                34 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.inner)?;
                },
                42 => {
                    self.items.push(is.read_message()?);
                },
                48 => {
                    self.count = is.read_int32()?;
                },
                56 => {
                    self.kind = is.read_enum_or_unknown()?;
                },
                66 => {
                    self.payload = ::std::option::Option::Some(record::Payload::Text(is.read_string()?));
                },
                74 => {
                    self.payload = ::std::option::Option::Some(record::Payload::Nested(is.read_message()?));
                },
                850 => {
                    self.payload = ::std::option::Option::Some(record::Payload::Blob(is.read_bytes()?));
                },
                82 => {
                    let len = is.read_raw_varint32()?;
                    let old_limit = is.push_limit(len as u64)?;
                    let mut key = ::std::default::Default::default();
                    let mut value = ::std::default::Default::default();
                    while let Some(tag) = is.read_raw_tag_or_eof()? {
                        match tag {
                            10 => key = is.read_string()?,
                            18 => value = is.read_string()?,
                            _ => ::protobuf::rt::skip_field_for_tag(tag, is)?,
                        };
                    }
                    is.pop_limit(old_limit);
                    self.attrs.insert(key, value);
                },
                802 => {
                    self.extra_scalar = is.read_string()?;
                },
                810 => {
                    self.extra_optional = ::std::option::Option::Some(is.read_string()?);
                },
                818 => {
                    self.extra_repeated.push(is.read_string()?);
                },
                826 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.extra_message)?;
                },
                834 => {
                    let len = is.read_raw_varint32()?;
                    let old_limit = is.push_limit(len as u64)?;
                    let mut key = ::std::default::Default::default();
                    let mut value = ::std::default::Default::default();
                    while let Some(tag) = is.read_raw_tag_or_eof()? {
                        match tag {
                            10 => key = is.read_string()?,
                            18 => value = is.read_string()?,
                            _ => ::protobuf::rt::skip_field_for_tag(tag, is)?,
                        };
                    }
                    is.pop_limit(old_limit);
                    self.extra_map.insert(key, value);
                },
                840 => {
                    self.extra_varint = is.read_int64()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.title.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.title);
        }
        if let Some(v) = self.note.as_ref() {
            my_size += ::protobuf::rt::string_size(2, &v);
        }
        for value in &self.tags {
            my_size += ::protobuf::rt::string_size(3, &value);
        };
        if let Some(v) = self.inner.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        for value in &self.items {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        if self.count != 0 {
            my_size += ::protobuf::rt::int32_size(6, self.count);
        }
        if self.kind != ::protobuf::EnumOrUnknown::new(Kind::KIND_UNSPECIFIED) {
            my_size += ::protobuf::rt::int32_size(7, self.kind.value());
        }
        for (k, v) in &self.attrs {
            let mut entry_size = 0;
            entry_size += ::protobuf::rt::string_size(1, &k);
            entry_size += ::protobuf::rt::string_size(2, &v);
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(entry_size) + entry_size
        };
        if !self.extra_scalar.is_empty() {
            my_size += ::protobuf::rt::string_size(100, &self.extra_scalar);
        }
        if let Some(v) = self.extra_optional.as_ref() {
            my_size += ::protobuf::rt::string_size(101, &v);
        }
        for value in &self.extra_repeated {
            my_size += ::protobuf::rt::string_size(102, &value);
        };
        if let Some(v) = self.extra_message.as_ref() {
            let len = v.compute_size();
            my_size += 2 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        for (k, v) in &self.extra_map {
            let mut entry_size = 0;
            entry_size += ::protobuf::rt::string_size(1, &k);
            entry_size += ::protobuf::rt::string_size(2, &v);
            my_size += 2 + ::protobuf::rt::compute_raw_varint64_size(entry_size) + entry_size
        };
        if self.extra_varint != 0 {
            my_size += ::protobuf::rt::int64_size(105, self.extra_varint);
        }
        if let ::std::option::Option::Some(ref v) = self.payload {
            match v {
                &record::Payload::Text(ref v) => {
                    my_size += ::protobuf::rt::string_size(8, &v);
                },
                &record::Payload::Nested(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
                &record::Payload::Blob(ref v) => {
                    my_size += ::protobuf::rt::bytes_size(106, &v);
                },
            };
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.title.is_empty() {
            os.write_string(1, &self.title)?;
        }
        if let Some(v) = self.note.as_ref() {
            os.write_string(2, v)?;
        }
        for v in &self.tags {
            os.write_string(3, &v)?;
        };
        if let Some(v) = self.inner.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(4, v, os)?;
        }
        for v in &self.items {
            ::protobuf::rt::write_message_field_with_cached_size(5, v, os)?;
        };
        if self.count != 0 {
            os.write_int32(6, self.count)?;
        }
        if self.kind != ::protobuf::EnumOrUnknown::new(Kind::KIND_UNSPECIFIED) {
            os.write_enum(7, ::protobuf::EnumOrUnknown::value(&self.kind))?;
        }
        for (k, v) in &self.attrs {
            let mut entry_size = 0;
            entry_size += ::protobuf::rt::string_size(1, &k);
            entry_size += ::protobuf::rt::string_size(2, &v);
            os.write_raw_varint32(82)?; // Tag.
            os.write_raw_varint32(entry_size as u32)?;
            os.write_string(1, &k)?;
            os.write_string(2, &v)?;
        };
        if !self.extra_scalar.is_empty() {
            os.write_string(100, &self.extra_scalar)?;
        }
        if let Some(v) = self.extra_optional.as_ref() {
            os.write_string(101, v)?;
        }
        for v in &self.extra_repeated {
            os.write_string(102, &v)?;
        };
        if let Some(v) = self.extra_message.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(103, v, os)?;
        }
        for (k, v) in &self.extra_map {
            let mut entry_size = 0;
            entry_size += ::protobuf::rt::string_size(1, &k);
            entry_size += ::protobuf::rt::string_size(2, &v);
            os.write_raw_varint32(834)?; // Tag.
            os.write_raw_varint32(entry_size as u32)?;
            os.write_string(1, &k)?;
            os.write_string(2, &v)?;
        };
        if self.extra_varint != 0 {
            os.write_int64(105, self.extra_varint)?;
        }
        if let ::std::option::Option::Some(ref v) = self.payload {
            match v {
                &record::Payload::Text(ref v) => {
                    os.write_string(8, v)?;
                },
                &record::Payload::Nested(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(9, v, os)?;
                },
                &record::Payload::Blob(ref v) => {
                    os.write_bytes(106, v)?;
                },
            };
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Record {
        Record::new()
    }

    fn clear(&mut self) {
        self.title.clear();
        self.note = ::std::option::Option::None;
        self.tags.clear();
        self.inner.clear();
        self.items.clear();
        self.count = 0;
        self.kind = ::protobuf::EnumOrUnknown::new(Kind::KIND_UNSPECIFIED);
        self.payload = ::std::option::Option::None;
        self.payload = ::std::option::Option::None;
        self.payload = ::std::option::Option::None;
        self.attrs.clear();
        self.extra_scalar.clear();
        self.extra_optional = ::std::option::Option::None;
        self.extra_repeated.clear();
        self.extra_message.clear();
        self.extra_map.clear();
        self.extra_varint = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Record {
        static instance: ::protobuf::rt::Lazy<Record> = ::protobuf::rt::Lazy::new();
        instance.get(Record::new)
    }
}

impl ::protobuf::MessageFull for Record {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("Record").unwrap()).clone()
    }
}

impl ::std::fmt::Display for Record {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Record {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

/// Nested message and enums of message `Record`
pub mod record {

    #[derive(Clone,PartialEq,Debug)]
    #[non_exhaustive]
    // @@protoc_insertion_point(oneof:synthetic_extended_v1.Record.payload)
    pub enum Payload {
        // @@protoc_insertion_point(oneof_field:synthetic_extended_v1.Record.text)
        Text(::std::string::String),
        // @@protoc_insertion_point(oneof_field:synthetic_extended_v1.Record.nested)
        Nested(super::Inner),
        // @@protoc_insertion_point(oneof_field:synthetic_extended_v1.Record.blob)
        Blob(::std::vec::Vec<u8>),
    }

    impl ::protobuf::Oneof for Payload {
    }

    impl ::protobuf::OneofFull for Payload {
        fn descriptor() -> ::protobuf::reflect::OneofDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::OneofDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| <super::Record as ::protobuf::MessageFull>::descriptor().oneof_by_name("payload").unwrap()).clone()
        }
    }

    impl Payload {
        pub(in super) fn generated_oneof_descriptor_data() -> ::protobuf::reflect::GeneratedOneofDescriptorData {
            ::protobuf::reflect::GeneratedOneofDescriptorData::new::<Payload>("payload")
        }
    }
}

#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:synthetic_extended_v1.Kind)
pub enum Kind {
    // @@protoc_insertion_point(enum_value:synthetic_extended_v1.Kind.KIND_UNSPECIFIED)
    KIND_UNSPECIFIED = 0,
    // @@protoc_insertion_point(enum_value:synthetic_extended_v1.Kind.KIND_A)
    KIND_A = 1,
    // @@protoc_insertion_point(enum_value:synthetic_extended_v1.Kind.KIND_B)
    KIND_B = 2,
    // @@protoc_insertion_point(enum_value:synthetic_extended_v1.Kind.KIND_C)
    KIND_C = 3,
}

impl ::protobuf::Enum for Kind {
    const NAME: &'static str = "Kind";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<Kind> {
        match value {
            0 => ::std::option::Option::Some(Kind::KIND_UNSPECIFIED),
            1 => ::std::option::Option::Some(Kind::KIND_A),
            2 => ::std::option::Option::Some(Kind::KIND_B),
            3 => ::std::option::Option::Some(Kind::KIND_C),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<Kind> {
        match str {
            "KIND_UNSPECIFIED" => ::std::option::Option::Some(Kind::KIND_UNSPECIFIED),
            "KIND_A" => ::std::option::Option::Some(Kind::KIND_A),
            "KIND_B" => ::std::option::Option::Some(Kind::KIND_B),
            "KIND_C" => ::std::option::Option::Some(Kind::KIND_C),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [Kind] = &[
        Kind::KIND_UNSPECIFIED,
        Kind::KIND_A,
        Kind::KIND_B,
        Kind::KIND_C,
    ];
}

impl ::protobuf::EnumFull for Kind {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("Kind").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = *self as usize;
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for Kind {
    fn default() -> Self {
        Kind::KIND_UNSPECIFIED
    }
}

impl Kind {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<Kind>("Kind")
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x1bsynthetic_extended_v1.proto\x12\x15synthetic_extended_v1\"#\n\x05I\
    nner\x12\x0c\n\x01a\x18\x01\x20\x01(\tR\x01a\x12\x0c\n\x01b\x18\x02\x20\
    \x01(\tR\x01b\"$\n\x0cExtraMessage\x12\x14\n\x05value\x18\x01\x20\x01(\t\
    R\x05value\"\xe9\x06\n\x06Record\x12\x14\n\x05title\x18\x01\x20\x01(\tR\
    \x05title\x12\x17\n\x04note\x18\x02\x20\x01(\tH\x01R\x04note\x88\x01\x01\
    \x12\x12\n\x04tags\x18\x03\x20\x03(\tR\x04tags\x122\n\x05inner\x18\x04\
    \x20\x01(\x0b2\x1c.synthetic_extended_v1.InnerR\x05inner\x122\n\x05items\
    \x18\x05\x20\x03(\x0b2\x1c.synthetic_extended_v1.InnerR\x05items\x12\x14\
    \n\x05count\x18\x06\x20\x01(\x05R\x05count\x12/\n\x04kind\x18\x07\x20\
    \x01(\x0e2\x1b.synthetic_extended_v1.KindR\x04kind\x12\x14\n\x04text\x18\
    \x08\x20\x01(\tH\0R\x04text\x126\n\x06nested\x18\t\x20\x01(\x0b2\x1c.syn\
    thetic_extended_v1.InnerH\0R\x06nested\x12\x14\n\x04blob\x18j\x20\x01(\
    \x0cH\0R\x04blob\x12>\n\x05attrs\x18\n\x20\x03(\x0b2(.synthetic_extended\
    _v1.Record.AttrsEntryR\x05attrs\x12!\n\x0cextra_scalar\x18d\x20\x01(\tR\
    \x0bextraScalar\x12*\n\x0eextra_optional\x18e\x20\x01(\tH\x02R\rextraOpt\
    ional\x88\x01\x01\x12%\n\x0eextra_repeated\x18f\x20\x03(\tR\rextraRepeat\
    ed\x12H\n\rextra_message\x18g\x20\x01(\x0b2#.synthetic_extended_v1.Extra\
    MessageR\x0cextraMessage\x12H\n\textra_map\x18h\x20\x03(\x0b2+.synthetic\
    _extended_v1.Record.ExtraMapEntryR\x08extraMap\x12!\n\x0cextra_varint\
    \x18i\x20\x01(\x03R\x0bextraVarint\x1a8\n\nAttrsEntry\x12\x10\n\x03key\
    \x18\x01\x20\x01(\tR\x03key\x12\x14\n\x05value\x18\x02\x20\x01(\tR\x05va\
    lue:\x028\x01\x1a;\n\rExtraMapEntry\x12\x10\n\x03key\x18\x01\x20\x01(\tR\
    \x03key\x12\x14\n\x05value\x18\x02\x20\x01(\tR\x05value:\x028\x01B\t\n\
    \x07payloadB\x07\n\x05_noteB\x11\n\x0f_extra_optional*@\n\x04Kind\x12\
    \x14\n\x10KIND_UNSPECIFIED\x10\0\x12\n\n\x06KIND_A\x10\x01\x12\n\n\x06KI\
    ND_B\x10\x02\x12\n\n\x06KIND_C\x10\x03b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(3);
            messages.push(Inner::generated_message_descriptor_data());
            messages.push(ExtraMessage::generated_message_descriptor_data());
            messages.push(Record::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(1);
            enums.push(Kind::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
